# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

name: $(BuildID)

pool:
  vmImage: "ubuntu-latest"

steps:
- task: file-creator@5
  displayName: 'Env creation'
  inputs:
    fileoverwrite: true
    filepath: '.env'
    filecontent: |
      NODE_ENV=production
      VUE_APP_API=/api/

- task: Npm@1
  displayName: npm ci
  inputs:
    command: 'ci'

- task: Npm@1
  displayName: npm run build
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  displayName: publish build artifact studo-front-build
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'stu-do-front-build'