# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

name: $(BuildID)

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: build
  displayName: Build
  jobs:
  - job: buildFront
    steps:
      - task: file-creator@5
        displayName: 'Env creation'
        inputs:
          fileoverwrite: true
          filepath: '.env'
          filecontent: |
            NODE_ENV=production
            VUE_APP_API=/api/

      - task: Npm@1
        displayName: npm ci
        inputs:
          command: 'ci'

      - task: Npm@1
        displayName: npm run build
        inputs:
          command: 'custom'
          customCommand: 'run build'

      - publish: dist
        artifact: studo-front-build
      - task: Docker@2
        inputs:
          containerRegistry: 'rtuitlab connection by admin'
          repository: 'rtuitlab/studo-front'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            $(Build.BuildId)
            latest